### PR TITLE
Handle URL Params

### PR DESCRIPTION
**Pull request by olivernyc**
- Set config based on query params
- Save config to query params
- Download button is blue
- Refactored the code (added some redux boilerplate, but should be more maintainable now)

### CODE REVIEW

**Comment by zgiles** [comment]
hmm.. umm. I appreciate all the extra code, but upon first look, I wonder -- do we need all this extra code, redux, etc? I like redux for other things, but is it too much for this small app?
It's true that the state is a little unmanageable, so I could see it helping with that.

I didn't know you were doing this or I wouldnt have spend a few days making it generate clean download names. I think that's all going to have to get thrown out now..

**Comment by olivernyc** [comment]
I agree, not sure we need redux. Happy to rework this into something simpler.. I'm not attached to any of the code.

I do think splitting up the components and adding react-router are good changes.

Where is the clean download names code? Did you make any other changes? I don't see why we would have to throw it out.

**Comment by zgiles** [comment]
*waited forever for npm install* gotta love nodejs :) 
I gave it a try, it does work, and functions better than the old code, so that's a huge +. There were edge cases where the old code would get stuck and need a reload.
Download doesnt function though.. something's off there.
I dont quite understand the component/Component/component, but I'm sure that's just me :)

The download rename code was pretty simple. I didn't push it. Basically iteration 1 was swapping this in:
`
_tmplrealname = () =>
       var filename = "config.txt"
      if (this.state.config.nodenumber && this.state.config.file !== undefined)  {
              filename = this.state.config.file.replace(".tmpl", "").replace("nnnn", this.state.config.nodenumber)
      } else {
              filename = this.state.config.file.replace(".tmpl", "")
      }
      return filename
}
`
To allow filenames to have an `nnnn` in them and if node number happens to be a config value then it uses it. This way we can still have non-node-number files too.

The second iteration I've been working on would pull a meta.json in the folder to get additional parameters for a device so that you could have fancy names for the Template instead of just the file name. And download could be a more complex string. But, I didn't get that to work yet. Was stuck in the old `Promise.all` section of code.  
Probably redux would actually help this because loading json files by filtering the output of the json code two ways was not very trivial.

**Comment by olivernyc** [comment]
Cool, I fixed the download button, added `nnnn` support and fetching `meta.json`.

**Pull request merged**
